name: PhoenixSchwarzmarkt
version: '1.3'
main: com.bocktom.schwarzmarkt.Schwarzmarkt
api-version: '1.21'
depend:
  - Vault
  - LuckPerms
commands:
  schwarzmarkt:
    description: Schwarzmarkt Befehl
    usage: /schwarzmarkt <setup|start|stop|info|show|bieten|gewinne|titel|setinvitem> [args]
    permission: schwarzmarkt.use
permissions:
  schwarzmarkt.use:
    description: Erlaubt die Nutzung des Schwarzmarkt Befehl für User
    default: true
  schwarzmarkt.admin:
    description: Erlaubt die Nutzung der Schwarzmarkt Befehle für Admins
    default: op
